version: "3.8"
services:
    consumer_backend:
      build: 
        context: .
        dockerfile: ./Dockerfile
      stop_signal: SIGINT
      container_name: consumer_backend
      image: consumer_backend
      ports:
        - "9002:9002"
      # ? For automatically updating the container (for development only)
      volumes:
        - .:/app
      restart: always
      networks:
        - default

    consumer_database:
      image: mongo
      container_name: consumer_db_service
      ports:
        - "27018:27017"
      volumes:
        - /usr/local/var/mongodb/consumer:/data/db
      restart: unless-stopped
      networks:
        - default

networks:
  default:
    name: messaging_system